In [1]:
import os

import tensorflow as tf
from tensorflow import keras
from keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
import numpy as np
from PIL import Image as pil_image

print(tf.version.VERSION)

2022-02-11 14:31:38.822148: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-02-11 14:31:38.822173: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


2.6.0


In [2]:
#checkpoint_path = "training_1/cp.ckpt"
#checkpoint_dir = os.path.dirname(checkpoint_path)

In [3]:
# Recreate the exact same model, including its weights and the optimizer
model = tf.keras.models.load_model('../saved_model/my_butterfly_model', compile = True)

# Show the model architecture
model.summary()

2022-02-11 14:31:40.372409: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-02-11 14:31:40.372436: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-02-11 14:31:40.372455: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (lion-tva2): /proc/driver/nvidia/version does not exist
2022-02-11 14:31:40.372693: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 160, 160, 3)]     0         
_________________________________________________________________
sequential_1 (Sequential)    (None, 160, 160, 3)       0         
_________________________________________________________________
tf.math.truediv_1 (TFOpLambd (None, 160, 160, 3)       0         
_________________________________________________________________
tf.math.subtract_1 (TFOpLamb (None, 160, 160, 3)       0         
_________________________________________________________________
mobilenetv2_1.00_160 (Functi (None, 5, 5, 1280)        2257984   
_________________________________________________________________
global_average_pooling2d_1 ( (None, 1280)              0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 1280)              0   

In [4]:
# Evaluate the restored model
#loss, acc = model.evaluate(test_images, test_labels, verbose=2)
#print('Restored model, accuracy: {:5.2f}%'.format(100 * acc))

#print(model.predict(test_images).shape)

In [25]:
import numpy as np

import gradio as gr
import matplotlib.pyplot as plt
from keras.preprocessing.image import load_img, img_to_array

def classify_image(input_img):
    img = input_img
    #img = input_img.resize((160, 160), resample=pil_image.BICUBIC)
    arr = img_to_array(img)
    print(arr)
    #img = load_img(input_img)
    # Inside the classify_image function
    #img = img.resize((160, 160), resample=pil_image.BICUBIC)
    
    #arr = np.expand_dims(arr, axis=0)
    #arr /= 255
    #score = model.predict(arr)
    
    arr = np.expand_dims(arr, axis=0)
    arr /= 255
    # Inside the classify_image function
    score = model.predict(arr)
    
    return ('moth' if score < 0.5 else 'butterfly', float(score))


iface = gr.Interface(classify_image, gr.inputs.Image(shape=(160, 160)), "image")

iface.launch()

Running on local URL:  http://127.0.0.1:7881/

To create a public link, set `share=True` in `launch()`.


(<fastapi.applications.FastAPI at 0x7fcb04660340>,
 'http://127.0.0.1:7881/',
 None)

[[[208. 208. 210.]
  [209. 209. 211.]
  [214. 214. 216.]
  ...
  [ 89.  85.  62.]
  [ 89.  85.  61.]
  [ 90.  85.  62.]]

 [[206. 206. 208.]
  [209. 209. 211.]
  [213. 213. 215.]
  ...
  [ 81.  78.  57.]
  [ 86.  81.  59.]
  [ 89.  84.  64.]]

 [[209. 209. 211.]
  [209. 209. 211.]
  [211. 211. 213.]
  ...
  [ 69.  66.  47.]
  [ 73.  69.  50.]
  [ 77.  73.  54.]]

 ...

 [[ 73.   8.  12.]
  [ 70.   9.  11.]
  [ 69.  12.   9.]
  ...
  [  3.   3.   5.]
  [  3.   3.   5.]
  [  3.   3.   5.]]

 [[ 75.   9.  13.]
  [ 72.  10.  12.]
  [ 71.  12.  10.]
  ...
  [  3.   3.   5.]
  [  3.   3.   5.]
  [  3.   3.   5.]]

 [[ 74.  11.  15.]
  [ 71.  13.  14.]
  [ 68.  13.  11.]
  ...
  [  3.   3.   5.]
  [  3.   3.   5.]
  [  3.   3.   5.]]]


Traceback (most recent call last):
  File "/home/t.vaghjee/Documents/tools/python/anaconda3/lib/python3.8/site-packages/gradio/app.py", line 199, in predict
    prediction, durations = await run_in_threadpool(
  File "/home/t.vaghjee/Documents/tools/python/anaconda3/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/t.vaghjee/Documents/tools/python/anaconda3/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/t.vaghjee/Documents/tools/python/anaconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/t.vaghjee/Documents/tools/python/anaconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/t.vaghje